### ISSUE TITLE
how to customize layout of advisers' children?

### ISSUE THREAD

**Issue by cfm** [BasicPrimitives/javascript#12]
A [graph](https://gist.github.com/cfm/ab3da4e27f865ed868bf358d4d510bef) and the configuration—

    {
        enablePanning: true,
        hasButtons: primitives.common.Enabled.False,
        hasSelectorCheckbox: primitives.common.Enabled.False,
        minimalVisibility: primitives.common.Visibility.Normal,
        navigationMode: primitives.common.NavigationMode.Cursor,
        neighborSelectionMode: primitives.common.NeighboursSelectionMode.ParentsChildrenSiblingsAndSpouses,
        pageFitMode: primitives.common.PageFitMode.PageHeight,
    }

—displays with the the last "adviser's" children always placed
between the "adviser" row and all other "adviser's" children:

<img width="1837" alt="Screen Shot 2019-08-21 at 15 32 00" src="https://user-images.githubusercontent.com/357435/63473195-6f35a280-c429-11e9-8e8c-ce5f11792339.png">

The desired display has all "advisers" and their children on the same
rows:

<img width="1460" alt="Screenshot 2019-08-21 15 40 02" src="https://user-images.githubusercontent.com/357435/63473403-28947800-c42a-11e9-93ae-2efd03378b70.png">

Is this layout possible?

**Comment by BasicPrimitives** [comment]
Use disconnected hierarchies combined with straight connector annotation, see following samples:
Root items:
https://www.basicprimitives.com/usecases/multiplerootitemsinchart
Annotations:
https://www.basicprimitives.com/usecases/connectorannotation
Switch to straight annotations.

**Comment by cfm** [comment]
Thank you!  This looks like it will work.  I’d hoped to be able to use
the “adviser” nodes as lateral parents, in order to support
highlight-path annotations that would propagate up from a given
hierarchy and then across the "adviser" row in the direction of the
parent relationships.  But I can make the connector annotations dynamic
to the same effect.

I appreciate your help.

**Comment by BasicPrimitives** [comment]
Children push down is done on purpose to place advisers close to parent, it is not a big deal to make it optional.

**Comment by BasicPrimitives** [comment]
We added option supporting your layout
![image](https://user-images.githubusercontent.com/2230139/69692695-de620900-10a0-11ea-9f71-0475f0f14791.png)

**Comment by cfm** [comment]
Please accept my belated thanks for adding the `placeAdvisorsAboveChildren` parameter.  I've been able to adopt it for my use-case, and it works beautifully.
