### ISSUE TITLE
Loading information dynamicly

### ISSUE THREAD

**Issue by takuy** [BasicPrimitives/javascript#14]
Hi, I've been looking at BasicPrimitives' functionality, hoping to integrate it into an app. 

The library looks fantastic, feature-filled and will definitely fulfill almost every need I have!

However, I am not sure if I'm just missing an example on this, but I am looking to render only part of an organizational chart and allow endusers to expand/collapse the tree as needed. If a node has children, the children don't instantly show up but the node knows it has children. You "expand" that node down, loading the information from the server (AJAX), and then those children become part of the tree. The same could be done for expanding a node "up" to explore managers, siblings, etc. 

Is behavior like this possible? 

My thought was to use the ButtonPanel, but if there's a way to add interactive arrows or something similar, that would work as well?

**Comment by BasicPrimitives** [comment]
Yes, definitely we support this mode of nodes loading, it is our primary use case to load diagram nodes. See dynamic nodes loading demo:
https://www.basicprimitives.com/dynamicloading

The source code of this demo is available in  github repository:
https://github.com/BasicPrimitives/react-demo/tree/master/src/containers/Demos/DynamicLoading

**Comment by BasicPrimitives** [comment]
It looks like you are not using react, so for you a regular JavaScript Demo can be more handy
https://basicprimitives.github.io/javascript/samples/javascript.controls/DemoDynamicLoading.html

And just in case, here is the link to jQuery demo as well. 
https://basicprimitives.github.io/javascript/samples/jquery.widgets/DemoLargeHierarchy.html
