### ISSUE TITLE
No hints in buttons

### ISSUE THREAD

**Issue by mberiam** [BasicPrimitives/javascript#15]
I reported an issue on Tue, 21 May 2019, about missing buttons hints in each diagram node. Do you have any prediction when this feature will work again? TIA!

**Comment by BasicPrimitives** [comment]
jQuery changed tooltip API, that is why they stopped working
![image](https://user-images.githubusercontent.com/2230139/64119932-f576b080-cd68-11e9-8b1c-d5549baea342.png)
Clone this repository for latest jQuery API.
