### ISSUE TITLE
When ItemConfig "Image" property set to null, 404 error

### ISSUE THREAD

**Issue by moshulu** [BasicPrimitives/javascript#25]
Hello.
When I try to leave out the Family ItemConfig "image" property, my webpage tries to send a GET request to a relative "null" page, instead of BasicPrimitives registering there is no image provided and leaving it out. For example:

...
image: null
...

In console...
GET xyz.com/null 404 error

Any way of leaving out the picture in a family tree diagram?

**Comment by BasicPrimitives** [comment]
What is the version you are talking about? JS, PDF or React?

Please, send your code snippet to support email.

**Comment by moshulu** [comment]
JS v5.5.0. Sent to the support email. Thanks for your help.
