### ISSUE TITLE
Render label annotations in SelectionOnly PageFitMode

### ISSUE THREAD

**Issue by oreoeo** [BasicPrimitives/javascript#32]
Is it possible to render LabelAnnotations for a family diagram while the PageFitMode is set to SelectionOnly? In my chart I move from an "expanded" view (PageFitMode set to None) to a view minimizing specific nodes and leaving others expanded (PageFitMode set to SelectionOnly). When the PageFitMode is set to None the label annotations I have created render no problem, but once I switch over to SelectionOnly mode the annotations no longer appear on the diagram. Any insight you can provide is helpful, thanks.

**Comment by BasicPrimitives** [comment]
Hi, This is design behavior. In the  `SelectionOnly` mode, all nodes are collapsed into dots, so Label Annotations are supposed to be rendered as dots as well. Keeping them full size disables auto-fit mode. Labels and any text in general are non-scalable visual elements, they have minimal size requirements from UX perspective, so we ether need to keep them visible or hide completely.

Please, explain why you consider this behavior to be a bug.

**Comment by ord4** [comment]
In my use of the `SelectionOnly` I am choosing these specific nodes I wish to display and I would also like to show the annotations relevant to those nodes that I have selected.
![image](https://user-images.githubusercontent.com/15524821/75482338-a0f86a80-5972-11ea-9992-5e27dc0cf854.png)
Based on the picture you can see that I am selecting the specific nodes I wish to view maximized and minimized. If I can select the nodes I want to view I would think that I should have some ability to select the annotations as well and display them between my maximinzed nodes, just like in my expanded view. 
![image](https://user-images.githubusercontent.com/15524821/75482611-2845de00-5973-11ea-80f0-08cc49803c21.png)
This may not be a bug of the `SelectionOnly` mode, but rather a limitation? Or, is there another `PageFitMode` that would better suit these needs.

**Comment by BasicPrimitives** [comment]
Accepted. It would be fixed.

**Comment by BasicPrimitives** [comment]
![image](https://user-images.githubusercontent.com/2230139/112727533-488af800-8ef9-11eb-8924-612a59154dd7.png)
This issue is not reproducible anymore.
