### ISSUE TITLE
BasicPrimitives Annotation

### ISSUE THREAD

**Issue by drcmomo** [BasicPrimitives/javascript#36]
Hello,
I would like to know if it is possible to add annotations between two items.
for example an annotation of 25% between SOFIDIV SAS and LVMH INC.
You have an idea? Thank you in advance

![image](https://user-images.githubusercontent.com/18593208/78113329-dd9b0400-73ff-11ea-8d0d-a6249fa304de.png)

**Comment by BasicPrimitives** [comment]
See following sample
https://github.com/BasicPrimitives/javascript/blob/master/samples/ItemTemplateLabel.md
You don't need to create Annotation, if you are using a regular orgDiagram, you just need to place Labels outside of your nodes boundaries.

**Comment by BasicPrimitives** [comment]
See the following example as well:
https://www.basicprimitives.com/usecases/labelscascadesinfamilychart
