### ISSUE TITLE
Issue in custom template

### ISSUE THREAD

**Issue by patilvasudeo** [BasicPrimitives/javascript#39]
Hi, 

I am using custom template for chart with different color for each item. 
Initial loading is working perfectly as expected.  But if I scroll the chart to left or right, suddenly node color, description changes with next node.

Working perfectly with default template, but facing issue with custom template

Can we use default template without images?

**Comment by BasicPrimitives** [comment]
Look at implementation of default template:
https://github.com/BasicPrimitives/javascript/blob/master/src.primitives/Controls/OrgDiagram/Templates/ItemTemplate.js

```JavaScript
  function render(event, data) {
    var itemConfig = data.context,
      itemTitleColor = itemConfig.itemTitleColor != null ? itemConfig.itemTitleColor : primitives.common.Colors.RoyalBlue,
      color = primitives.common.highestContrast(itemTitleColor, options.itemTitleSecondFontColor, options.itemTitleFirstFontColor),
      element = data.element,
      titleBackground = element.firstChild,
      photo = element.childNodes[1].firstChild,
      title = titleBackground.firstChild,
      description = element.childNodes[2];

    primitives.common.JsonML.applyStyles(titleBackground, {
      "backgroundColor": itemTitleColor
    });
    photo.src = itemConfig.image;
    photo.alt = itemConfig.title;
    primitives.common.JsonML.applyStyles(title, {
      "color": color
    });
    title.textContent = itemConfig.title;
    description.textContent = itemConfig.description;
  }
```

**Comment by patilvasudeo** [comment]
tried this, but somehow not able to solve the issue. Will you help me with sample family chart with 9-10 node with different colour

**Comment by BasicPrimitives** [comment]
See following sample:
https://basicprimitives.github.io/javascript/samples/javascript.controls/DemoTechTree.html
Its source code is here:
https://github.com/BasicPrimitives/javascript/blob/master/samples/javascript.controls/DemoTechTree.html

It works.
