### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by luchmewep** [BasicPrimitives/javascript#44]
A pleasant day to you, guys! This is really awesome! Keep the amazing work! 💯

Will there be a possibility in the future that you might add Typescript support?
It would really be awesome if we can just see the options or functions available with just a simple ctrl+space. 😅

I hope you can provide Typescript support soon. Best of luck! 😁

**Comment by BasicPrimitives** [comment]
Our product is being developed in [ECMAScript® 2015 Language Specification](http://www.ecma-international.org/ecma-262/6.0/)
