### ISSUE TITLE
Package Name

### ISSUE THREAD

**Issue by luchmewep** [BasicPrimitives/javascript#45]
Good day!

So far, this is the easiest org chart package I used! Thanks for this!

But it really took me a while to find this amazing package. 😅 Will you be able to rename this package in the future? I'm sure it will be downloaded more often if its name is much more related to organization chart or family tree or organization tree. It really did took me a long time to find this that I gave up middleway.

Kudos!

**Comment by BasicPrimitives** [comment]
Internet Search is not our business. The fact that you cannot find us is a result of Google's work.  As of today their capitalization is $1.18T. I think they just don't care about search results anymore, their business is something different.
