### ISSUE TITLE
relativeItem not working as expected

### ISSUE THREAD

**Issue by jpmous** [BasicPrimitives/javascript#54]
I am using basicprimitives to display a genealogy tree.

I am trying to display the wife at the right of her husband using "relativeItem" . For example adding on one item :

placementType: 2
position: 1
relativeItem: "196"

But it does not work as expected even on small tree. See Helena G. here. On bigger tree all is mixed.
![bs_tree_bad](https://user-images.githubusercontent.com/24922358/106356486-3416ee80-6300-11eb-80ec-1f2f9d2f6311.png)

I tried to set relativeItem and placementType on only one or both of spouses, but it is not displayed better. I tried to sort the array, having first the husband then his wife, but not better.

relativeitem seems not to work properly. Or am I missing something ?

Regards. JP

**Comment by BasicPrimitives** [comment]
Yes, it is a bug. For now, set Remigius on the right of Joannes. Don't use `spouses` collection property. We are going to deprecate this feature in the next round of famDiagram upgrades. Use explicit custom diagram nodes to show marriages instead.

**Comment by jpmous** [comment]
I have not yet succeeded.
I removed all "spouses". Added one fake node per marriage.
I left almost all wives on the right.
I set Remigius on the right of Joannes. Not good. I tried to set Remigius on the right of Marie G. Same.
Here is the result:
![genea2](https://user-images.githubusercontent.com/24922358/106938885-d3344f80-671f-11eb-8a5a-04388413da89.png)

**Comment by BasicPrimitives** [comment]
![image](https://user-images.githubusercontent.com/2230139/106969199-67021d80-6718-11eb-840b-28d8847a2210.png)

```JavaScript
  items: [
    { id: 1, title: "Joannes", groupTitleColor: "#0000FF", groupTitle: "Male", description: "1", image: "../images/photos/d.png", itemTitleColor: "#4169e1" },
    { id: 2, title: "Marie", relativeItem: 1, placementType: primitives.AdviserPlacementType.Right, position: 1, groupTitleColor: "#FF0000", groupTitle: "Female", description: "2", image: "../images/photos/m.png", itemTitleColor: "#4169e1" },
    { id: 3, parents: [1, 2], title: "Wedding", description: "3", image: "../images/photos/w.png", itemTitleColor: "#4169e1" },
    { id: 6, parents: [3], title: "Jacombus", relativeItem: 5, placementType: primitives.AdviserPlacementType.Right, position: 1, groupTitleColor: "#0000FF", groupTitle: "Male", description: "3rd child", image: "../images/photos/d.png", itemTitleColor: "#4169e1" },

    { id: 7, title: "Remigius", relativeItem: 1, placementType: primitives.AdviserPlacementType.Right, position: 1, groupTitleColor: "#0000FF", groupTitle: "Male", description: "7", image: "../images/photos/n.png", itemTitleColor: "#4169e1" },
    { id: 8, title: "Helena", relativeItem: 7, placementType: primitives.AdviserPlacementType.Right, position: 1, groupTitleColor: "#FF0000", groupTitle: "Female", description: "8", image: "../images/photos/p.png", itemTitleColor: "#4169e1" },
    { id: 9, parents: [7, 8], title: "Wedding", description: "9", image: "../images/photos/w.png", itemTitleColor: "#4169e1" },

    { id: 10, parents: [9], title: "Helena", groupTitleColor: "#FF0000", groupTitle: "Female", description: "10", image: "../images/photos/n.png", itemTitleColor: "#4169e1" },
    { id: 11, parents: [6, 10], title: "Wedding", description: "11", image: "../images/photos/w.png", itemTitleColor: "#4169e1" },

    { id: 22, parents: [11], title: "Karolus", relativeItem: 21, placementType: primitives.AdviserPlacementType.Right, position: 1, groupTitleColor: "#0000FF", groupTitle: "Male", description: "2nd child", image: "../images/photos/d.png", itemTitleColor: "#4169e1" },

    { id: 27, parents: [20], title: "Maria", relativeItem: 22, placementType: primitives.AdviserPlacementType.Right, position: 1, groupTitleColor: "#FF0000", groupTitle: "Female", description: "27", image: "../images/photos/t.png", itemTitleColor: "#4169e1" },
    { id: 28, parents: [27, 22], title: "1st Wedding", description: "26, Divorced", image: "../images/photos/w.png", itemTitleColor: "#4169e1" },
  ]
```

**Comment by BasicPrimitives** [comment]
Yes, we need to account for relations defined in the middle of the diagram as well.

**Comment by jpmous** [comment]
I do not know what I did wrong for my second example but following yours it works.
I have to figure out how to code that for a dynamic tree (to build among hundreds of persons).
Many thanks for your answer and software.
JP
