### ISSUE TITLE
Frame padding is always added to the outside of the frame

### ISSUE THREAD

**Issue by buesing** [BasicPrimitives/javascript#61]
I have a family diagram that looks like this (diagram on the right side):
![image](https://user-images.githubusercontent.com/1181371/113564052-fb99d680-9608-11eb-88de-a277d5adb94c.png)

I would like to add a padding to it, so it doesn't stick so close to the menu on the left. So I tried `frameInnerPadding` which looks like this):
![image](https://user-images.githubusercontent.com/1181371/113564103-0bb1b600-9609-11eb-95d7-2ef725b91328.png)

This looks like the padding is being applied outside of the frame? Also, the padding only seems to work when `showFrame === true`. But I don't want to display a frame, I just want a padding. I can't use CSS padding on the container, because that produces an ugly empty area when the diagram is scrolled:
![image](https://user-images.githubusercontent.com/1181371/113564558-deb1d300-9609-11eb-9d41-68a75523ec66.png)

 Maybe there is another way to accomplish this that I'm not aware of? Thanks!

**Comment by BasicPrimitives** [comment]
The 'frameInnerPadding' property is used for padding markers on the margin
![image](https://user-images.githubusercontent.com/2230139/113614876-1b3cf900-9621-11eb-89f5-958861632c6a.png)

**Comment by BasicPrimitives** [comment]
See `normalItemsInterval` property
![image](https://user-images.githubusercontent.com/2230139/113615246-9f8f7c00-9621-11eb-93cc-d0de9641316e.png)
![image](https://user-images.githubusercontent.com/2230139/113615418-d82f5580-9621-11eb-977d-91ba31f62421.png)

**Comment by buesing** [comment]
Hey, thanks for the quick reply. I just tried this, it seems to be for setting the space between nodes, but I just want to set the space at the borders. This is the edge of the diagram with `normalItemsInterval` set to 100:

![image](https://user-images.githubusercontent.com/1181371/113617276-74734f80-9656-11eb-93f4-987bab92a779.png)

You can see that on the left side, there is no padding between the node and the diagram border.

**Comment by BasicPrimitives** [comment]
![image](https://user-images.githubusercontent.com/2230139/113620569-7c1bff80-9628-11eb-8536-c994ffc8c997.png)
![image](https://user-images.githubusercontent.com/2230139/113620650-9eae1880-9628-11eb-83c7-5e98353860ac.png)

**Comment by BasicPrimitives** [comment]
Ok. Would you like to have a dedicated property for extra padding around diagram?
It probably makes sense to eliminate any implicit paddings.

**Comment by buesing** [comment]
Interesting, your example doesn't work for my diagram.. Yes, that would be amazing! Thanks!

**Comment by BasicPrimitives** [comment]
What is your setting for `pageFitMode` property?
![image](https://user-images.githubusercontent.com/2230139/113621276-71ae3580-9629-11eb-9600-dbd0fac0051f.png)

**Comment by buesing** [comment]
It's `PageFitMode.None`, but just tried `PageFitMode.FitToPage`, that also didn't work.
This is my full config:
```
  const config = {
    enableMatrixLayout: true,
    minimumMatrixSize: 3,
    maximumColumnsInMatrix: 10,
    selectionPathMode: SelectionPathMode.FullStack,
    hasSelectorCheckbox: Enabled.False,
    pageFitMode: PageFitMode.None,
    showLabel: Enabled.False,
    items: getItems(props),
    annotations: getAnnotations(props),
    defaultTemplateName: 'basic',
    templates: [
      {
        name: 'basic',
        itemSize: { width: 220, height: 100 },
        minimizedItemSize: { width: 3, height: 3 },
        isActive: false,
        onItemRender: ChartItem,
      },
      {
        name: 'label',
        itemSize: { width: 80, height: 20 },
        highlightPadding: { left: 0, top: 0, right: 0, bottom: 0 },
        onItemRender: ChartLabel,
      },
    ],
  }
```

**Comment by BasicPrimitives** [comment]
Are you sure that your drawer is not overlapping diagram?

**Comment by buesing** [comment]
Yes, here is the drawer with reduced opacity and the diagram with a background to visually confirm this:
![image](https://user-images.githubusercontent.com/1181371/113623409-996bc080-965e-11eb-9c28-637cba14688a.png)

**Comment by BasicPrimitives** [comment]
Yes, it is Family Diagram layout bug. Fix is needed.

![image](https://user-images.githubusercontent.com/2230139/113623707-b8515f00-962c-11eb-8c70-304ca2af1ac1.png)

**Comment by BasicPrimitives** [comment]
Fixed in 6.3.1.

**Comment by buesing** [comment]
Nice, thanks. So that is working now. If we could have an additional dedicated property to just control the padding of the diagram, that would be amazing. I don't need this much space between the nodes.
![image](https://user-images.githubusercontent.com/1181371/113677045-6d335c80-96bd-11eb-862c-c849e1a81068.png)

**Comment by BasicPrimitives** [comment]
See normalItemsInterval property
![image](https://user-images.githubusercontent.com/2230139/113711548-10cb3f80-96b3-11eb-92b9-03ff12b33495.png)

**Comment by buesing** [comment]
Hey, the `normalItemsInterval` works now, but it controls the spacing between all nodes. I would like to control just the spacing between the outermost nodes and the diagram edge. Could you add another property for this?

**Comment by BasicPrimitives** [comment]
Added `padding` option to org and family charts, it will be available starting version 6.4.0

**Comment by buesing** [comment]
Hey, just came back to this to test, and it seems it doesn't work at least iin the react version? Was this only added to the JS version? Thanks

**Comment by BasicPrimitives** [comment]
See `padding` property in the Intervals tab
https://www.basicprimitives.com/highlightannotations
Pay attention that it is Thickness structure, padding = { left: 10, top: 100, right: 10, bottom:10};
