### ISSUE TITLE
Will support be added for spouse/couple relationships in Family Charts?

### ISSUE THREAD

**Issue by GashyDev** [BasicPrimitives/javascript#78]
Hi I've been using the BasicPrimitives library for a family tree project, and it has been working perfectly until I realised that two people won't have a connection unless they have a child, which isn't ideal because not every couple has a child. This results in the person just floating at the top of the diagram.

I've noticed that this (or something similar at least) was removed in a previous version so I've had to downgrade, which isn't ideal for future-proofing. Will this be introduced again in a future update?

// Issue with 6.4
![image](https://user-images.githubusercontent.com/34476863/140967790-2dd11dd6-e8cc-4e30-b928-a3ad0bb16a12.png)

// example of the wanted relationship from what I get in 6.2.2
![image](https://user-images.githubusercontent.com/34476863/140969474-cab3f714-272a-4cea-bb47-21e293c7379b.png)

**Comment by BasicPrimitives** [comment]
We are simplifying our project. The `spouses` collection property is redundant in many usage scenarious.  In the majority of use cases, we need to have an explicit Marriage node. The answer is no, we don't plan to reintroduce that property back. The workaround is to add an invisible child node for spouses if they have no children.
