### ISSUE TITLE
PDF issue while generating from view - Hindi Lang

### ISSUE THREAD

**Issue by abhishekbhalani** [BasicPrimitives/javascript#80]
Hi,

We are facing issue while using Hindi language to generate PDF.
It rendering unknown characters in PDF file.

any solutions for it?
attached screenshot here.
![pdf_multiLang](https://user-images.githubusercontent.com/1845707/144590316-b8cc59a4-6933-4e23-ad4f-246f1c64726a.png)

**Comment by BasicPrimitives** [comment]
Our library used PDFKit API to render diagrams in DDF. We don't alter any default settings of the PDF context, so when App creates PDF Document we rely on its settings. See the following article about the issue:
https://stackoverflow.com/questions/27649435/using-pdfkit-in-node-js-to-render-text-in-any-language

**Comment by BasicPrimitives** [comment]
See PDFKit reference for custom fonts usage:
https://pdfkit.org/docs/text.html#fonts
