### ISSUE TITLE
Samples dont work

### ISSUE THREAD

**Issue by fasteddys** [BasicPrimitives/javascript#99]
Hello I tried with CORS allowed, and with VS code live server for localhost, both dont show any of the orgcharts, can you please share some guidance.

![image](https://user-images.githubusercontent.com/96149622/196331075-9fb96b34-c5d6-4cf1-a554-0e8156c2bf86.png)

**Comment by BasicPrimitives** [comment]
We are github project, please, use `yarn` or `npm` to start webpack dev server

```
yarn start
```
open http://localhost:8080/

If you need to run it at your web site, then build it with `yarn build`

See package.json for available scripts:

```
  "scripts": {
    "test": "jest",
    "build": "webpack",
    "start": "webpack serve ",
    "apireference": "node apireference.js apireference.json"
  },
```
